---
# VAULT - Génération d'un mot de passe avec une policy
- name: "{{ titre_vault_generate }} - Generation mot de passe avec la policy {{ tmp_vault_gen_password_policy }}"
  ansible.builtin.uri:
   url: "{{ vault_info.url }}/{{ vault_info.version }}/sys/policies/password/{{ tmp_vault_gen_password_policy }}/generate"
   method: GET
   return_content: yes
   status_code: 200
   validate_certs: false
   headers:
     X-Vault-Token: "{{ tmp_vault_token }}"
  no_log: "{{ ansible_no_log }}"
  delegate_to: localhost
  become: false
  register: test_generate_password

# On formatte la variable de sortie/retour pour envoyer le mot de passe généré
- name: "{{ titre_vault_generate }} - Formattage de la variable de retour du mot de passe généré."
  ansible.builtin.set_fact:
    tmp_generate_vault_password: "{{ test_generate_password.json.data.password }}"
  no_log: "{{ ansible_no_log }}"
  
...